CREATE TABLE IF NOT EXISTS public.user_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  event_type TEXT NOT NULL,
  event_name TEXT NOT NULL,
  message TEXT,
  source TEXT,
  route TEXT,
  request_id TEXT,
  session_id TEXT,
  task_id UUID,
  metadata JSONB,
  prompt TEXT,
  response TEXT,
  model TEXT,
  provider TEXT,
  status_code INTEGER,
  duration_ms INTEGER,
  error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);